CREATE TABLE AUTHORITIES(
    USER_NO NUMBER REFERENCES MEMBER,
    AUTHORITY VARCHAR2(15),
    PRIMARY KEY(USER_NO, AUTHORITY)
);

INSERT INTO authorities VALUES(11, 'ROLE_ADMIN');
INSERT INTO authorities VALUES(11, 'ROLE_USER');
